# Generated by Django 3.2.6 on 2021-08-16 11:05

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_page', models.CharField(max_length=40, unique=True, verbose_name='Имя страницы')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Логотип компании')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('city', models.CharField(max_length=30, verbose_name='Город (Предложный.падеж)')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
            },
        ),
    ]
