# Generated by Django 3.2.6 on 2021-09-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_clientchoice_type_door'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientchoice',
            name='color_door',
            field=models.CharField(choices=[('white', 'Белый'), ('wood', 'Под дерево'), ('black', 'Чёрный'), ('fresh', 'Цветной'), ('another', 'Другой')], default='another', max_length=50, verbose_name='Цвет'),
        ),
    ]
