# Generated by Django 3.2.6 on 2021-09-02 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_clientchoice_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientchoice',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.pageshop', verbose_name='Магазин'),
        ),
    ]
