# Generated by Django 3.1.4 on 2021-02-10 08:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dveri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitka',
            name='city_title',
            field=models.CharField(blank='True', max_length=30, null='False', verbose_name='Город (Предложный.падеж)'),
            preserve_default='False',
        ),
        migrations.AddField(
            model_name='visitka',
            name='email_adress',
            field=models.EmailField(default='et@vvs-kaluga.ru', max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='visitka',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='visitka',
            name='name_page',
            field=models.CharField(blank='True', max_length=30, unique='True', verbose_name='Имя страницы'),
        ),
    ]
